# Generated by Django 5.0.6 on 2024-06-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='sees',
            field=models.IntegerField(default=3, verbose_name='Sees'),
        ),
    ]
