# Generated by Django 5.0.6 on 2024-06-27 04:44

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Welcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_1', models.CharField(max_length=255, verbose_name='Name 1')),
                ('title_1', models.TextField(verbose_name='Title 1')),
                ('image_1', models.ImageField(upload_to=main.models.upload_image, verbose_name='Image 1')),
                ('name_2', models.CharField(max_length=255, verbose_name='Name 2')),
                ('title_2', models.TextField(verbose_name='Title 2')),
                ('image_2', models.ImageField(upload_to=main.models.upload_image, verbose_name='Image 2')),
            ],
        ),
    ]
